name: "Lite Voyager"
# Training Parameters
batch_size: 128
learning_rate: 0.001
learning_rate_decay: 2
min_learning_rate: 0.0001
num_epochs: 10
num_epochs_online: 5
steps_per_epoch: 1000
train_split: 0.8
valid_split: 0.1
multi_label: False
# Input Parameters
sequence_loss: False
use_current_pc: False
sequence_length: 8
offset_bits: 6
prediction_depth: 0
global_stream: False
pc_localized: True
use_deltas: True
# LSTM Parameters
pc_embed_size: 32
page_embed_size: 64
num_experts: 10
lstm_size: 64
lstm_dropout: 0.1
lstm_layers: 1
# Output Parameters
global_output: False
max_delta_pages: 32
